config/routes.rb
Anarchum::Application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'

  resources :categories, :except => [:index, :show]
  resources :forums, :except => :index do
    resources :topics, :shallow => true, :except => :index do
      resources :posts, :shallow => true, :except => [:index, :show]
    end
    root :to => 'categories#index', :via => :get
  end

  match "/faq",     to: 'static_pages#faq'
  match "/about",   to: 'static_pages#about'

  get "static_pages/about"

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login',    to: 'devise/sessions#new',       as: :login
    get '/logout',    to: 'devise/sessions#destroy',       as: :logout
  end
  
  devise_for :users
  resources :users

end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  hits        :integer          default(0)
#  sticky      :boolean          default(FALSE)
#  locked      :boolean          default(FALSE)
#  posts_count :integer
#  forum_id    :integer
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Topic < ActiveRecord::Base
  
  # Associations
  has_many :posts, :dependent => :destroy
  belongs_to :forum, :counter_cache => true
  belongs_to :user, :class_name => "User", :counter_cache => true
  
  # Accessors
  attr_accessor :body
  attr_accessible :title, :body, :sticky, :locked, :forum_id
  
  # Validations
  validates :title,   :presence => true
  validates :body,    :presence => true, :on => :create
  validates :posts,   :presence => true, :allow_nil => false, :on => :update
  validates :user,    :presence => true
  
  # Scopes
  default_scope :order => 'sticky DESC, updated_at DESC'
  
  # Callbacks
  after_create :create_initial_post
  
  # Methods
  def hit!
    self.class.increment_counter :hits, id
  end
  
  private
    def create_initial_post
      self.posts.build(:body => self.body).tap do |post|
        post.forum = self.forum
        post.user = self.user
        post.save
      end
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  load_and_authorize_resource :forum
  load_and_authorize_resource :topic, :through => :forum, :shallow => true
  
  def show
    @topic.hit! if @topic
  end
  
  def create
    @topic.user ||= current_user
    
    if @topic.save
      flash[:notice] = "Topic was successfully created."
      redirect_to topic_url(@topic)
    else
      render :action => 'new'
    end
  end
  
  def update
    if @topic.update_attributes(params[:topic])
      flash[:notice] = "Topic was updated successfully."
      redirect_to topic_url(@topic)
    end
  end

  def destroy
    if @topic.destroy
      flash[:notice] = "Topic was deleted successfully."
      redirect_to forum_url(@topic.forum)
    end
  end
  
end

app/views/topics/_form.html.erb
<%= form_for [@forum, @topic] do |f| %>
<% if @topic.errors.any? %>
  <% flash.now[:error] = @topic.errors.full_messages.join(', and ') %>
<% end %>
<div class="module">
  <div class="module_header"><%= action_name.humanize %> Topic</div>
    <div class="module_subheader smaller"></div>
    <div class="module_body">
      <div class="fieldset forum-label">
        <span class="label indent smaller">
          <%= f.label :title %>
          <small>(Required)</small>
        </span>
        <span class="input indent smaller"><%= f.text_field :title, :size => 75 %></span>
        <div class="clear"></div>
      </div><br />
      <% unless @topic.id %>
      <div class="fieldset forum-label">
        <span class="label indent smaller">
          <%= f.label :body %>
          <small>(Required)</small>
        </span>
        <span class="input indent smaller"><%= f.text_area :body, :cols => 100, :rows => 15 %></span>
        <div class="clear"></div>
      </div>
    </div>
    <% end %>
    <div class="module_footer">
      <div class="fieldset">
        <span class="input"><%= f.submit "submit", :class => "btn btn-primary-custom span2 forum-submit" %> or <%= link_to "cancel", @topic.nil? ?  @topic : @forum %></span>
        <div class="clear"></div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/topics/edit.html.erb
<%= render :partial => 'form' %>

app/views/topics/new.html.erb
<%= render :partial => 'form' %>

app/views/topics/show.html.erb
<div class="right controls"><%= link_to "Back to Forum", forum_path(@topic.forum) %></div>
<div class="module">
  <div class="module_header">
    <%= @topic.title %>
    <span class="right controls">        
      <% if current_user && current_user.admin? %>
        <%= link_to "Edit", edit_topic_path(@topic) %>
        <%= link_to "Delete", @topic, :confirm => "Are you sure?", :method => :delete %>
        <%= link_to @topic.sticky ? "Unstick" : "Sticky", {:controller => 'topics', :action => 'update', :topic => {:sticky => @topic.sticky ? "false" : "true" }}, :method => :put %>
        <%= link_to @topic.locked ? "Unlock" : "Lock", {:controller => 'topics', :action => 'update', :topic => {:locked => @topic.locked ? "false" : "true" }}, :method => :put %>
      <% end %>
    </span>
  </div>
  <div>
    <table>
      <% @topic.posts.each do |post| %>
      <tr>
        <td class="post_author" rowspan="2">
          <span class="name"><%= post.user.username %></span>
          <span class="avatar"><!-- This space reserved for Avatar --></span>
          <span class="info smaller">
            Post Count: <%= post.user.posts.size %><br />
            Registered on <%= post.user.created_at.strftime("%F") %><br />
          </span>
        </td>
        <td class="post_header">
          <span class="left post_date smaller">Posted <%= post.created_at %></span>
          <span class="right controls">
              <%= link_to "Reply", new_topic_post_path(@topic) %>
              <%= link_to "Quote", new_topic_post_path(@topic, :quote => post) %>
            <% if (post.user == current_user) || current_user.admin? %>
              <%= link_to "Edit", edit_post_path(post) %>
              <%= link_to "Delete", post, :confirm => "Are you sure?", :method => :delete %>
            <% end %>
          </span>
        </td>
      </tr>
      <tr>
        <td class="post_body">
          <%= post.body.html_safe %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>