config/routes.rb
Anarchum::Application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'

  resources :categories, :except => [:index, :show]
  resources :forums, :except => :index do
    resources :topics, :shallow => true, :except => :index do
      resources :posts, :shallow => true, :except => [:index, :show]
    end
    root :to => 'categories#index', :via => :get
  end

  match "/faq",     to: 'static_pages#faq'
  match "/about",   to: 'static_pages#about'

  get "static_pages/about"

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login',    to: 'devise/sessions#new',       as: :login
    get '/logout',    to: 'devise/sessions#destroy',       as: :logout
  end
  
  devise_for :users
  resources :users

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to image_tag("anarchumcrown.png"), root_path, :class => 'brand' %>
<ul class="nav pull-right">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="false">
        About <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
        <li><%= link_to "FAQ", faq_path %></li>
        <li class="divider"></li>
        <li><%= link_to "About", about_path %></li>
    </ul>
</li>
  <li><a href="#">Blog</a></li>
  <li><%= link_to "Forums", forums_path %></li>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
    <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Anarchum <%= yield(:title) %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Anarchum" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <link href='http://fonts.googleapis.com/css?family=Jacques+Francois' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Allerta' rel='stylesheet' type='text/css'>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="container">
    <div class="navbar">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
        <% if user_signed_in? %>
          <div class="span4 offset8">
            Logged in as <strong><%= current_user.username %></strong>
          </div>
        <% end %>
      </nav>
    </div>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  
<script>
  $(document).ready(function(){  
    $('form[data-remote]').bind("ajax:before", function(){
      for (instance in CKEDITOR.instances){
        CKEDITOR.instances[instance].updateElement();
      }
    });
  });
</script>
  </body>
</html>